# Generated by Django 5.0.1 on 2024-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nut_info',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagePath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='nutInfo',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
