# Generated by Django 5.0.1 on 2024-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_produto_nut_info_produto_imagepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagePath',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nutInfo',
            field=models.CharField(max_length=400),
        ),
    ]
