# Generated by Django 5.0.1 on 2024-02-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_produto_imagepath_alter_produto_nutinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='inView',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
